Repository Icinga/icinga-notifications, pull requests merged in 2023-10, with the labels that each got.

#104 Add git versions for builds and http responses
  .gitattributes
  cmd/icinga-notifications-daemon/main.go
  internal/listener/listener.go
  internal/version.go
Labels: cla/signed

#109 icinga2.conf: urlencode service and host names
  icinga2.conf
Labels: cla/signed

#100 Reference channels by their ID
  internal/config/channel.go
  internal/config/contact.go
  internal/config/rule.go
  internal/config/runtime.go
  internal/config/verify.go
  internal/incident/db_types.go
  internal/incident/incident.go
  internal/recipient/contact.go
  internal/rule/escalation.go
  schema/pgsql/schema.sql
  schema/pgsql/upgrades/016.sql
Labels: cla/signed, enhancement

#113 GitHub Actions: remove duplicate job names
  .github/workflows/docker.yml
  .github/workflows/go.yml
Labels: cla/signed, github_actions

#117 golangci-lint: add as a CI and fix raised concerns
  .github/workflows/go.yml
  internal/incident/incident.go
  internal/listener/listener.go
  internal/object/object.go
Labels: cla/signed
