Repository Icinga/icinga-notifications, pull requests merged in 2023-09, with the labels that each got.

#86 Add Dockerfile
  .github/workflows/docker.yml
  Dockerfile
Labels: cla/signed

#87 Add `membership_hash` column to `schedule_member` table
  schema/pgsql/schema.sql
  schema/pgsql/upgrades/014.sql
Labels: cla/signed

#79 Init incident rules on daemon startup
  internal/incident/incident.go
  internal/incident/incidents.go
Labels: bug, cla/signed

#76 Use `sqlx.Tx` for event processing
  go.sum
  internal/event/event.go
  internal/incident/db_types.go
  internal/incident/incident.go
  internal/incident/incidents.go
  internal/incident/sync.go
  internal/listener/listener.go
  internal/object/object.go
  internal/utils/utils.go
Labels: cla/signed, enhancement
