Repository Icinga/icinga-notifications, pull requests merged in 2024-07, with the labels that each got.

#210 doc: Initialize documentation
  Makefile
  README.md
  config.example.yml
  doc/01-About.md
  doc/02-Installation.md
  doc/02-Installation.md.d/From-Source.md
  doc/03-Configuration.md
  doc/04-Upgrading.md
  doc/05-Distributed-Setups.md
  doc/10-Channels.md
  doc/20-HTTP-API.md
  doc/30-Development.md
  doc/images/icinga-notifications-architecture.png
Labels: cla/signed

#229 doc/01-About.md: Remove relative link outside doc
  doc/01-About.md
Labels: cla/signed, doc

#191 Incremental Configuration Updates
  internal/channel/channel.go
  internal/config/baseconf/incremental_config.go
  internal/config/channel.go
  internal/config/contact.go
  internal/config/contact_address.go
  internal/config/group.go
  internal/config/incremental_sync.go
  internal/config/rule.go
  internal/config/runtime.go
  internal/config/schedule.go
  internal/config/source.go
  internal/config/timeperiod.go
  internal/incident/incident.go
  internal/incident/incidents_test.go
  internal/object/objects_test.go
  internal/recipient/contact.go
  internal/recipient/group.go
  internal/recipient/rotations.go
  internal/recipient/rotations_test.go
  internal/recipient/schedule.go
  internal/rule/escalation.go
  internal/rule/rule.go
  internal/timeperiod/timeperiod.go
  schema/pgsql/schema.sql
  schema/pgsql/upgrades/032.sql
Labels: cla/signed

#226 Schema: name all constraints, not just PKs
  internal/incident/db_types.go
  schema/pgsql/schema.sql
  schema/pgsql/upgrades/033.sql
Labels: cla/signed

#206 Channel default value by changing default logic
  cmd/channels/email/main.go
  cmd/channels/email/main_test.go
  cmd/channels/rocketchat/main.go
  cmd/channels/webhook/main.go
  pkg/plugin/plugin.go
Labels: cla/signed

#219 icinga2: Enhance debug logging
  internal/icinga2/api_responses.go
  internal/icinga2/client_api.go
Labels: cla/signed, enhancement

#234 Add AUTHORS and .mailmap
  .mailmap
  AUTHORS
Labels: cla/signed

#243 icinga2: Reset `Event#ID` before resending ack set event
  internal/icinga2/client_api.go
Labels: bug, cla/signed

#236 Increase details of Channels documentation
  doc/10-Channels.md
  doc/20-HTTP-API.md
  internal/channel/examples/get-info.json
  internal/channel/examples/send-notification.json
  internal/channel/examples/set-config.json
  pkg/plugin/plugin.go
Labels: cla/signed, enhancement, doc

#230 Ignore flapping state if flapping detection isn't enabled
  internal/icinga2/api_responses.go
  internal/icinga2/client.go
  internal/icinga2/client_api.go
  internal/icinga2/util.go
Labels: bug, cla/signed

#244 Fix warnings during docker build
  Dockerfile
Labels: cla/signed

#246 icinga2: Common Muted Event for Acknowledgements w/o Comments during Catch-Up
  internal/icinga2/client_api.go
Labels: bug, cla/signed

#247 Remove old icinga2.conf
  icinga2.conf
Labels: cla/signed

#239 Schema: don't limit browser_session.user_agent to 4096 chars
  schema/mysql/schema.sql
  schema/mysql/upgrades/035.sql
  schema/pgsql/schema.sql
  schema/pgsql/upgrades/035.sql
Labels: cla/signed

#248 Document `api-timeout` & config options in `config.example.yml`
  config.example.yml
  doc/03-Configuration.md
Labels: cla/signed, enhancement

#249 Docker GHA: Upload Docker images on release
  .github/workflows/docker.yml
Labels: cla/signed

#260 Container images: show git commit hash in --version output when built on GitHub Actions
  .github/workflows/docker.yml
Labels: bug, cla/signed

#251 listener: Don't error w/ 500 for superfluous events
  internal/listener/listener.go
Labels: cla/signed, enhancement

#268 Version 0.1.1
  CHANGELOG.md
  internal/version.go
Labels: cla/signed
