Repository Icinga/icinga-notifications, pull requests merged in 2025-04, with the labels that each got.

#305 golangci-lint: Address issues and config
  .github/workflows/go.yml
  .golangci.yml
  cmd/channels/rocketchat/main.go
  cmd/icinga-notifications/main.go
  internal/channel/plugin.go
  internal/config/verify.go
  internal/icinga2/client.go
  internal/listener/listener.go
  internal/object/object.go
Labels: cla/signed, github_actions

#306 Make unit tests compile on 32 bit
  internal/object/objects_test.go
Labels: cla/signed

#276 Use utils.IterateOrderedMap() as intended, via for:=range (require Go 1.23)
  internal/utils/utils.go
  internal/utils/utils_test.go
  pkg/plugin/plugin.go
Labels: cla/signed, go
